Added logic for KtisisHyperboreia.cs dungeon level 87
TheManta/RBtrust pull request #15
Opened 2022-06-26 17:10 UTC by KaiserBh

Pain :(

2022-07-03 00:19 UTC, TheManta requested changes
Thanks for submitting both dungeons -- it looks good! I was able to run both as DPS, and I appreciate the sub-zone checks for boss mechanics + defining spell lists outside of `RunAsync()`.

Before I approve this, please fix the line-specific comments below and then resolve any StyleCop/.editorconfig stuff in Visual Studio's "Error List"/Rider's "Problems" tab. Fixing the specific items first will shrink the list to just a few style things, so definitely tackle those first.

2022-07-03 17:47 UTC, KaiserBh commented on Plugins/Trust/Dungeons/KtisisHyperboreia.cs
> +            if (WorldManager.SubZoneId == 3766)
![image](https://user-images.githubusercontent.com/41852205/177051387-84edc39e-7976-436b-82eb-ac7603a6737e.png)
seem to be an issue when checking these.

2022-07-03 17:57 UTC, KaiserBh commented on Plugins/Trust/Dungeons/TheAitiascope.cs
> +            if (WorldManager.SubZoneId == 3992)
Tried to change as many as I can but I am having issues regarding using the SubZoneId.EnumOftheZone.

2022-07-03 17:57 UTC, KaiserBh commented
Tried to change as many as I can but I am having issues regarding using the SubZoneId.EnumOftheZone.

2022-07-03 19:45 UTC, TheManta commented on Plugins/Trust/Dungeons/KtisisHyperboreia.cs
> +            if (WorldManager.SubZoneId == 3766)
`WorldManager.SubZoneId` is `uint` and the enum `SubZoneId` is backed by `uint`, so it's 100% safe to do this so we can keep the nice sub-zone names:
```suggestion
            if (WorldManager.SubZoneId == 3766)
            if (WorldManager.SubZoneId == (unit)SubZoneId.FrozenSphere)
```

2022-07-04 05:51 UTC, TheManta approved these changes

2022-07-04 06:11 UTC, merged

2022-07-04 06:12 UTC, TheManta commented
Awesome, thanks again for making changes and playing along with me figuring out GitHub code reviews <3