Added dodge Queer Bubble
TheManta/RBtrust pull request #18
Opened 2022-07-02 14:11 UTC by domesticwarlord86

2022-07-02 22:14 UTC, TheManta requested changes
I wanted to practice GitHub code reviews, so here we are.

Most issues can be fixed in Rider by going to `Problems (Alt-8) > Current File` and reading the ⚠️ items shown. "Typos" in monster names and "async method doesn't await" error on `RunAsync()` can be ignored. Leaving unused boss name => NpcId constants is also fine.

![image](https://user-images.githubusercontent.com/62259674/177017504-126f0df7-4023-4998-bfd3-1355a6ca0777.png)

2022-07-02 22:14 UTC, TheManta commented on Plugins/Trust/Dungeons/BrayfloxsLongstop.cs
> +
Code should not contain consecutive empty lines, per Style Cop ruleset.

2022-07-02 22:14 UTC, TheManta commented on Plugins/Trust/Dungeons/BrayfloxsLongstop.cs
> +            if (hellbenderNpc != null && hellbenderNpc.IsValid)
Unless `hellbenderNpc` will be used in a future iteration, remove the `GetObjectsByNPCId()` and change this condition to check for boss arena sub-zone and if we're in combat.

As-is, this spends time every tick throughout the dungeon searching for an NPC to be allowed to search for the NPC we care about. Removing the unnecessary Hellbender search and limiting it to searching the Queer Bubble only when in the right place will improve performance for the whole dungeon run.

2022-07-03 01:44 UTC, domesticwarlord86 commented on Plugins/Trust/Dungeons/BrayfloxsLongstop.cs
> +        private const int bubbleObj = 1383;
Fixed

2022-07-03 01:44 UTC, domesticwarlord86 commented on Plugins/Trust/Dungeons/BrayfloxsLongstop.cs
> +
fixed

2022-07-03 01:44 UTC, domesticwarlord86 commented on Plugins/Trust/Dungeons/BrayfloxsLongstop.cs
> +            if (hellbenderNpc != null && hellbenderNpc.IsValid)
fixed

2022-07-03 01:44 UTC, domesticwarlord86 commented
Should be fixed

2022-07-04 06:19 UTC, TheManta approved these changes

2022-07-04 06:24 UTC, merged